env:
  browser: true
  es2021: true
extends:
  - plugin:vue/essential
  - standard
  - './.eslintrc-auto-import.json'
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
rules: {
  'vue/multi-word-component-names': 0,
  'vue/no-multiple-template-root': 0,
  'vue/no-v-model-argument': 0,
  'vue/no-v-for-template-key': 0,
  'func-call-spacing': 0
}
