/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BatchChangeDelayModal: typeof import('./src/components/layout/framesSection/BatchChangeDelayModal.vue')['default']
    CheckOutlined: typeof import('@ant-design/icons-vue')['CheckOutlined']
    CloseOutlined: typeof import('@ant-design/icons-vue')['CloseOutlined']
    CustomSelect: typeof import('./src/components/common/formItem/CustomSelect.vue')['default']
    DownOutlined: typeof import('@ant-design/icons-vue')['DownOutlined']
    EyeInvisibleOutlined: typeof import('@ant-design/icons-vue')['EyeInvisibleOutlined']
    EyeOutlined: typeof import('@ant-design/icons-vue')['EyeOutlined']
    FileImageOutlined: typeof import('@ant-design/icons-vue')['FileImageOutlined']
    FormItem: typeof import('./src/components/common/formItem/FormItem.vue')['default']
    FrameItem: typeof import('./src/components/layout/framesSection/FrameItem.vue')['default']
    FramesSection: typeof import('./src/components/layout/framesSection/index.vue')['default']
    InputNumberSlider: typeof import('./src/components/common/formItem/InputNumberSlider.vue')['default']
    LayerItem: typeof import('./src/components/layout/layersSection/LayerItem.vue')['default']
    LayersSection: typeof import('./src/components/layout/layersSection/index.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    MenuOutlined: typeof import('@ant-design/icons-vue')['MenuOutlined']
    MoreMenu: typeof import('./src/components/layout/MoreMenu.vue')['default']
    MoreOperations: typeof import('./src/components/layout/framesSection/MoreOperations.vue')['default']
    Operations: typeof import('./src/components/layout/framesSection/Operations.vue')['default']
    RedoOutlined: typeof import('@ant-design/icons-vue')['RedoOutlined']
    StylesSection: typeof import('./src/components/layout/StylesSection.vue')['default']
    ToolbarSection: typeof import('./src/components/layout/ToolbarSection.vue')['default']
    UndoOutlined: typeof import('@ant-design/icons-vue')['UndoOutlined']
    UpOutlined: typeof import('@ant-design/icons-vue')['UpOutlined']
  }
}
